#define ANIMATION_DATA_CLKDIV 4
#define ANIMATION_DATA_PULSE 104
#define ANIMATION_DATA_BIT_0 2
#define ANIMATION_DATA_BIT_1 15
#define ANIMATION_DATA_STOP_PULSES 40
#define ANIMATION_DATA_IMAGES 4
#define ANIMATION_DATA_IMAGE_SIZE 192

enum{
	ANIMATION_DATA_IMAGE_1,
	ANIMATION_DATA_IMAGE_2,
	ANIMATION_DATA_IMAGE_3,
	ANIMATION_DATA_IMAGE_4
};